version: '3'

services:
  mavros_test_sitl:
    build:
      context: .
      dockerfile: docker/sitl.dockerfile
    container_name: mavros_test_sitl
    network_mode: host

  mavros:
    build:
      context: .
      dockerfile: docker/mavros.dockerfile
    container_name: mavros_test_mavros_node
    network_mode: host
    command: 'bash'
    # command: ["ros2", "run", "mavros", "mavros_node", "--ros-args", "--params-file", "mavros/mavros/launch/apm_config.yaml"]
    volumes:
      - .:/user/mavros_test/
    tty: true
